export type ImageType = {
  src: string
  alt: string
  category?: string
}

// Function to convert filename to readable title
export const getReadableTitle = (filename: string) => {
  return filename
    .replace('.jpg', '')
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

// Function to get category from filename
export const getCategory = (filename: string) => {
  const filenameWithoutExtension = filename.replace('.jpg', '');
  const parts = filenameWithoutExtension.split('_');
  if (parts.length > 1) {
    return parts[parts.length - 1].toLowerCase();
  }
  return '';
}

// Function to get all images from the public/images directory
export const getImages = () => {
  // This will be populated at build time
  const images: ImageType[] = [
    { src: "/images/Backyard_portal_entropy.jpg", alt: "Backyard Portal", category: "entropy" },
    { src: "/images/Bedroom_portal_entropy.jpg", alt: "Bedroom Portal", category: "entropy" },
    { src: "/images/BedoomPortal_2_entropy.jpg", alt: "Bedroom Portal 2", category: "entropy" },
    { src: "/images/Bridget_Lai_01_entropy.jpg", alt: "Bridget Lai 01", category: "entropy" },
    { src: "/images/Bridget_Lai_02_entropy.jpg", alt: "Bridget Lai 02", category: "entropy" },
    { src: "/images/Bridget_Lai_03_entropy.jpg", alt: "Bridget Lai 03", category: "entropy" },
    { src: "/images/Bridget_Lai_04_entropy.jpg", alt: "Bridget Lai 04", category: "entropy" },
    { src: "/images/Bridget_Lai_05_entropy.jpg", alt: "Bridget Lai 05", category: "entropy" },
    { src: "/images/Bridget_Lai_06_entropy.jpg", alt: "Bridget Lai 06", category: "entropy" },
    // Blog images with correct paths and extensions
    { src: "/images/blog/bridget_262_blog.jpeg", alt: "Blog 262", category: "blog" },
    { src: "/images/blog/bridget_261_blog.jpeg", alt: "Blog 261", category: "blog" },
    { src: "/images/blog/bridget_260_blog.jpeg", alt: "Blog 260", category: "blog" },
    { src: "/images/blog/bridget_259_blog.jpeg", alt: "Blog 259", category: "blog" },
    { src: "/images/blog/bridget_258_blog.jpeg", alt: "Blog 258", category: "blog" },
    { src: "/images/blog/bridget_257_blog.jpeg", alt: "Blog 257", category: "blog" },
    { src: "/images/blog/bridget_256_blog.jpeg", alt: "Blog 256", category: "blog" },
    { src: "/images/blog/bridget_255_blog.jpeg", alt: "Blog 255", category: "blog" },
    { src: "/images/blog/bridget_254_blog.jpeg", alt: "Blog 254", category: "blog" },
    { src: "/images/blog/bridget_253_blog.jpeg", alt: "Blog 253", category: "blog" },
    { src: "/images/blog/bridget_252_blog.jpeg", alt: "Blog 252", category: "blog" },
    { src: "/images/blog/bridget_251_blog.jpeg", alt: "Blog 251", category: "blog" },
    { src: "/images/blog/bridget_250_blog.jpeg", alt: "Blog 250", category: "blog" },
    { src: "/images/blog/bridget_249_blog.jpeg", alt: "Blog 249", category: "blog" },
    { src: "/images/blog/bridget_248_blog.jpeg", alt: "Blog 248", category: "blog" },
    { src: "/images/blog/bridget_247_blog.jpeg", alt: "Blog 247", category: "blog" },
    { src: "/images/blog/bridget_246_blog.jpeg", alt: "Blog 246", category: "blog" },
    { src: "/images/blog/bridget_245_blog.jpeg", alt: "Blog 245", category: "blog" },
    { src: "/images/blog/bridget_244_blog.jpeg", alt: "Blog 244", category: "blog" },
    { src: "/images/blog/bridget_243_blog.jpeg", alt: "Blog 243", category: "blog" },
    { src: "/images/blog/bridget_242_blog.jpeg", alt: "Blog 242", category: "blog" },
    { src: "/images/blog/bridget_241_blog.jpeg", alt: "Blog 241", category: "blog" },
    { src: "/images/blog/bridget_240_blog.jpeg", alt: "Blog 240", category: "blog" },
    { src: "/images/blog/bridget_239_blog.jpeg", alt: "Blog 239", category: "blog" },
    { src: "/images/blog/bridget_238_blog.jpeg", alt: "Blog 238", category: "blog" },
    { src: "/images/blog/bridget_237_blog.jpeg", alt: "Blog 237", category: "blog" },
    { src: "/images/blog/bridget_236_blog.jpeg", alt: "Blog 236", category: "blog" },
    { src: "/images/blog/bridget_235_blog.jpeg", alt: "Blog 235", category: "blog" },
    { src: "/images/blog/bridget_234_blog.jpeg", alt: "Blog 234", category: "blog" },
    { src: "/images/blog/bridget_233_blog.jpeg", alt: "Blog 233", category: "blog" },
    { src: "/images/blog/bridget_232_blog.jpeg", alt: "Blog 232", category: "blog" },
    { src: "/images/blog/bridget_231_blog.jpeg", alt: "Blog 231", category: "blog" },
    { src: "/images/blog/bridget_230_blog.jpeg", alt: "Blog 230", category: "blog" },
    { src: "/images/blog/bridget_229_blog.jpeg", alt: "Blog 229", category: "blog" },
    { src: "/images/blog/bridget_228_blog.jpeg", alt: "Blog 228", category: "blog" },
    { src: "/images/blog/bridget_227_blog.jpeg", alt: "Blog 227", category: "blog" },
    { src: "/images/blog/bridget_226_blog.jpeg", alt: "Blog 226", category: "blog" },
    { src: "/images/blog/bridget_225_blog.jpeg", alt: "Blog 225", category: "blog" },
    { src: "/images/blog/bridget_224_blog.jpeg", alt: "Blog 224", category: "blog" },
    { src: "/images/blog/bridget_223_blog.jpeg", alt: "Blog 223", category: "blog" },
    { src: "/images/blog/bridget_222_blog.jpeg", alt: "Blog 222", category: "blog" },
    { src: "/images/blog/bridget_221_blog.jpeg", alt: "Blog 221", category: "blog" },
    { src: "/images/blog/bridget_220_blog.jpeg", alt: "Blog 220", category: "blog" },
    { src: "/images/blog/bridget_219_blog.jpeg", alt: "Blog 219", category: "blog" },
    { src: "/images/blog/bridget_218_blog.jpeg", alt: "Blog 218", category: "blog" },
    { src: "/images/blog/bridget_217_blog.jpeg", alt: "Blog 217", category: "blog" },
    { src: "/images/blog/bridget_216_blog.jpeg", alt: "Blog 216", category: "blog" },
    { src: "/images/blog/bridget_215_blog.jpeg", alt: "Blog 215", category: "blog" },
    { src: "/images/blog/bridget_214_blog.jpeg", alt: "Blog 214", category: "blog" },
    { src: "/images/blog/bridget_213_blog.jpeg", alt: "Blog 213", category: "blog" },
    { src: "/images/blog/bridget_212_blog.jpeg", alt: "Blog 212", category: "blog" },
    { src: "/images/blog/bridget_211_blog.jpeg", alt: "Blog 211", category: "blog" },
    { src: "/images/blog/bridget_210_blog.jpeg", alt: "Blog 210", category: "blog" },
    { src: "/images/blog/bridget_209_blog.jpeg", alt: "Blog 209", category: "blog" },
    { src: "/images/blog/bridget_208_blog.jpeg", alt: "Blog 208", category: "blog" },
    { src: "/images/blog/bridget_207_blog.jpeg", alt: "Blog 207", category: "blog" },
    { src: "/images/blog/bridget_206_blog.jpeg", alt: "Blog 206", category: "blog" },
    { src: "/images/blog/bridget_205_blog.jpeg", alt: "Blog 205", category: "blog" },
    { src: "/images/blog/bridget_204_blog.jpeg", alt: "Blog 204", category: "blog" },
    { src: "/images/blog/bridget_203_blog.jpeg", alt: "Blog 203", category: "blog" },
    { src: "/images/blog/bridget_202_blog.jpeg", alt: "Blog 202", category: "blog" },
    { src: "/images/blog/bridget_201_blog.jpeg", alt: "Blog 201", category: "blog" },
    { src: "/images/blog/bridget_200_blog.jpeg", alt: "Blog 200", category: "blog" },
    { src: "/images/blog/bridget_199_blog.jpeg", alt: "Blog 199", category: "blog" },
    { src: "/images/blog/bridget_198_blog.jpeg", alt: "Blog 198", category: "blog" },
    { src: "/images/blog/bridget_197_blog.jpeg", alt: "Blog 197", category: "blog" },
    { src: "/images/blog/bridget_196_blog.jpeg", alt: "Blog 196", category: "blog" },
    { src: "/images/blog/bridget_195_blog.jpeg", alt: "Blog 195", category: "blog" },
    { src: "/images/blog/bridget_194_blog.jpeg", alt: "Blog 194", category: "blog" },
    { src: "/images/blog/bridget_193_blog.jpeg", alt: "Blog 193", category: "blog" },
    { src: "/images/blog/bridget_192_blog.jpeg", alt: "Blog 192", category: "blog" },
    { src: "/images/blog/bridget_191_blog.jpeg", alt: "Blog 191", category: "blog" },
    { src: "/images/blog/bridget_190_blog.jpeg", alt: "Blog 190", category: "blog" },
    { src: "/images/blog/bridget_189_blog.jpeg", alt: "Blog 189", category: "blog" },
    { src: "/images/blog/bridget_188_blog.jpeg", alt: "Blog 188", category: "blog" },
    { src: "/images/blog/bridget_187_blog.jpeg", alt: "Blog 187", category: "blog" },
    { src: "/images/blog/bridget_186_blog.jpeg", alt: "Blog 186", category: "blog" },
    { src: "/images/blog/bridget_185_blog.jpeg", alt: "Blog 185", category: "blog" },
    { src: "/images/blog/bridget_184_blog.jpeg", alt: "Blog 184", category: "blog" },
    { src: "/images/blog/bridget_183_blog.jpeg", alt: "Blog 183", category: "blog" },
    { src: "/images/blog/bridget_182_blog.jpeg", alt: "Blog 182", category: "blog" },
    { src: "/images/blog/bridget_181_blog.jpeg", alt: "Blog 181", category: "blog" },
    { src: "/images/blog/bridget_180_blog.jpeg", alt: "Blog 180", category: "blog" },
    { src: "/images/blog/bridget_179_blog.jpeg", alt: "Blog 179", category: "blog" },
    { src: "/images/blog/bridget_178_blog.jpeg", alt: "Blog 178", category: "blog" },
    { src: "/images/blog/bridget_177_blog.jpeg", alt: "Blog 177", category: "blog" },
    { src: "/images/blog/bridget_176_blog.jpeg", alt: "Blog 176", category: "blog" },
    { src: "/images/blog/bridget_175_blog.jpeg", alt: "Blog 175", category: "blog" },
    { src: "/images/blog/bridget_174_blog.jpeg", alt: "Blog 174", category: "blog" },
    { src: "/images/blog/bridget_173_blog.jpeg", alt: "Blog 173", category: "blog" },
    { src: "/images/blog/bridget_172_blog.jpeg", alt: "Blog 172", category: "blog" },
    { src: "/images/blog/bridget_171_blog.jpeg", alt: "Blog 171", category: "blog" },
    { src: "/images/blog/bridget_170_blog.jpeg", alt: "Blog 170", category: "blog" },
    { src: "/images/blog/bridget_169_blog.jpeg", alt: "Blog 169", category: "blog" },
    { src: "/images/blog/bridget_168_blog.jpeg", alt: "Blog 168", category: "blog" },
    { src: "/images/blog/bridget_167_blog.jpeg", alt: "Blog 167", category: "blog" },
    { src: "/images/blog/bridget_166_blog.jpeg", alt: "Blog 166", category: "blog" },
    { src: "/images/blog/bridget_165_blog.jpeg", alt: "Blog 165", category: "blog" },
    { src: "/images/blog/bridget_164_blog.jpeg", alt: "Blog 164", category: "blog" },
    { src: "/images/blog/bridget_163_blog.jpeg", alt: "Blog 163", category: "blog" },
    { src: "/images/blog/bridget_162_blog.jpeg", alt: "Blog 162", category: "blog" },
    { src: "/images/blog/bridget_161_blog.jpeg", alt: "Blog 161", category: "blog" },
    { src: "/images/blog/bridget_160_blog.jpeg", alt: "Blog 160", category: "blog" },
    { src: "/images/blog/bridget_159_blog.jpeg", alt: "Blog 159", category: "blog" },
    { src: "/images/blog/bridget_158_blog.jpeg", alt: "Blog 158", category: "blog" },
    { src: "/images/blog/bridget_157_blog.jpeg", alt: "Blog 157", category: "blog" },
    { src: "/images/blog/bridget_156_blog.jpeg", alt: "Blog 156", category: "blog" },
    { src: "/images/blog/bridget_155_blog.jpeg", alt: "Blog 155", category: "blog" },
    { src: "/images/blog/bridget_154_blog.jpeg", alt: "Blog 154", category: "blog" },
    { src: "/images/blog/bridget_153_blog.jpeg", alt: "Blog 153", category: "blog" },
    { src: "/images/blog/bridget_152_blog.jpeg", alt: "Blog 152", category: "blog" },
    { src: "/images/blog/bridget_151_blog.jpeg", alt: "Blog 151", category: "blog" },
    { src: "/images/blog/bridget_150_blog.jpeg", alt: "Blog 150", category: "blog" },
    { src: "/images/blog/bridget_149_blog.jpeg", alt: "Blog 149", category: "blog" },
    { src: "/images/blog/bridget_148_blog.jpeg", alt: "Blog 148", category: "blog" },
    { src: "/images/blog/bridget_147_blog.jpeg", alt: "Blog 147", category: "blog" },
    { src: "/images/blog/bridget_146_blog.jpeg", alt: "Blog 146", category: "blog" },
    { src: "/images/blog/bridget_145_blog.jpeg", alt: "Blog 145", category: "blog" },
    { src: "/images/blog/bridget_144_blog.jpeg", alt: "Blog 144", category: "blog" },
    { src: "/images/blog/bridget_143_blog.jpeg", alt: "Blog 143", category: "blog" },
    { src: "/images/blog/bridget_142_blog.jpeg", alt: "Blog 142", category: "blog" },
    { src: "/images/blog/bridget_141_blog.jpeg", alt: "Blog 141", category: "blog" },
    { src: "/images/blog/bridget_140_blog.jpeg", alt: "Blog 140", category: "blog" },
    { src: "/images/blog/bridget_139_blog.jpeg", alt: "Blog 139", category: "blog" },
    { src: "/images/blog/bridget_138_blog.jpeg", alt: "Blog 138", category: "blog" },
    { src: "/images/blog/bridget_137_blog.jpeg", alt: "Blog 137", category: "blog" },
    { src: "/images/blog/bridget_136_blog.jpeg", alt: "Blog 136", category: "blog" },
    { src: "/images/blog/bridget_135_blog.jpeg", alt: "Blog 135", category: "blog" },
    { src: "/images/blog/bridget_134_blog.jpeg", alt: "Blog 134", category: "blog" },
    { src: "/images/blog/bridget_133_blog.jpeg", alt: "Blog 133", category: "blog" },
    { src: "/images/blog/bridget_132_blog.jpeg", alt: "Blog 132", category: "blog" },
    { src: "/images/blog/bridget_131_blog.jpeg", alt: "Blog 131", category: "blog" },
    { src: "/images/blog/bridget_130_blog.jpeg", alt: "Blog 130", category: "blog" },
    { src: "/images/blog/bridget_129_blog.jpeg", alt: "Blog 129", category: "blog" },
    { src: "/images/blog/bridget_128_blog.jpeg", alt: "Blog 128", category: "blog" },
    { src: "/images/blog/bridget_127_blog.jpeg", alt: "Blog 127", category: "blog" },
    { src: "/images/blog/bridget_126_blog.jpeg", alt: "Blog 126", category: "blog" },
    { src: "/images/blog/bridget_125_blog.jpeg", alt: "Blog 125", category: "blog" },
    { src: "/images/blog/bridget_124_blog.jpeg", alt: "Blog 124", category: "blog" },
    { src: "/images/blog/bridget_123_blog.jpeg", alt: "Blog 123", category: "blog" },
    { src: "/images/blog/bridget_122_blog.jpeg", alt: "Blog 122", category: "blog" },
    { src: "/images/blog/bridget_121_blog.jpeg", alt: "Blog 121", category: "blog" },
    { src: "/images/blog/bridget_120_blog.jpeg", alt: "Blog 120", category: "blog" },
    { src: "/images/blog/bridget_119_blog.jpeg", alt: "Blog 119", category: "blog" },
    { src: "/images/blog/bridget_118_blog.jpeg", alt: "Blog 118", category: "blog" },
    { src: "/images/blog/bridget_117_blog.jpeg", alt: "Blog 117", category: "blog" },
    { src: "/images/blog/bridget_116_blog.jpeg", alt: "Blog 116", category: "blog" },
    { src: "/images/blog/bridget_115_blog.jpeg", alt: "Blog 115", category: "blog" },
    { src: "/images/blog/bridget_114_blog.jpeg", alt: "Blog 114", category: "blog" },
    { src: "/images/blog/bridget_113_blog.jpeg", alt: "Blog 113", category: "blog" },
    { src: "/images/blog/bridget_112_blog.jpeg", alt: "Blog 112", category: "blog" },
    { src: "/images/blog/bridget_111_blog.jpeg", alt: "Blog 111", category: "blog" },
    { src: "/images/blog/bridget_110_blog.jpeg", alt: "Blog 110", category: "blog" },
    { src: "/images/blog/bridget_109_blog.jpeg", alt: "Blog 109", category: "blog" },
    { src: "/images/blog/bridget_108_blog.jpeg", alt: "Blog 108", category: "blog" },
    { src: "/images/blog/bridget_107_blog.jpeg", alt: "Blog 107", category: "blog" },
    { src: "/images/blog/bridget_106_blog.jpeg", alt: "Blog 106", category: "blog" },
    { src: "/images/blog/bridget_105_blog.jpeg", alt: "Blog 105", category: "blog" },
    { src: "/images/blog/bridget_104_blog.jpeg", alt: "Blog 104", category: "blog" },
    { src: "/images/blog/bridget_103_blog.jpeg", alt: "Blog 103", category: "blog" },
    { src: "/images/blog/bridget_102_blog.jpeg", alt: "Blog 102", category: "blog" },
    { src: "/images/blog/bridget_101_blog.jpeg", alt: "Blog 101", category: "blog" },
    { src: "/images/blog/bridget_100_blog.jpeg", alt: "Blog 100", category: "blog" },
    { src: "/images/blog/bridget_099_blog.jpeg", alt: "Blog 99", category: "blog" },
    { src: "/images/blog/bridget_098_blog.jpeg", alt: "Blog 98", category: "blog" },
    { src: "/images/blog/bridget_097_blog.jpeg", alt: "Blog 97", category: "blog" },
    { src: "/images/blog/bridget_096_blog.jpeg", alt: "Blog 96", category: "blog" },
    { src: "/images/blog/bridget_095_blog.jpeg", alt: "Blog 95", category: "blog" },
    { src: "/images/blog/bridget_094_blog.jpeg", alt: "Blog 94", category: "blog" },
    { src: "/images/blog/bridget_093_blog.jpeg", alt: "Blog 93", category: "blog" },
    { src: "/images/blog/bridget_092_blog.jpeg", alt: "Blog 92", category: "blog" },
    { src: "/images/blog/bridget_091_blog.jpeg", alt: "Blog 91", category: "blog" },
    { src: "/images/blog/bridget_090_blog.jpeg", alt: "Blog 90", category: "blog" },
    { src: "/images/blog/bridget_089_blog.jpeg", alt: "Blog 89", category: "blog" },
    { src: "/images/blog/bridget_088_blog.jpeg", alt: "Blog 88", category: "blog" },
    { src: "/images/blog/bridget_087_blog.jpeg", alt: "Blog 87", category: "blog" },
    { src: "/images/blog/bridget_086_blog.jpeg", alt: "Blog 86", category: "blog" },
    { src: "/images/blog/bridget_085_blog.jpeg", alt: "Blog 85", category: "blog" },
    { src: "/images/blog/bridget_084_blog.jpeg", alt: "Blog 84", category: "blog" },
    { src: "/images/blog/bridget_083_blog.jpeg", alt: "Blog 83", category: "blog" },
    { src: "/images/blog/bridget_082_blog.jpeg", alt: "Blog 82", category: "blog" },
    { src: "/images/blog/bridget_081_blog.jpeg", alt: "Blog 81", category: "blog" },
    { src: "/images/blog/bridget_080_blog.jpeg", alt: "Blog 80", category: "blog" },
    { src: "/images/blog/bridget_079_blog.jpeg", alt: "Blog 79", category: "blog" },
    { src: "/images/blog/bridget_078_blog.jpeg", alt: "Blog 78", category: "blog" },
    { src: "/images/blog/bridget_077_blog.jpeg", alt: "Blog 77", category: "blog" },
    { src: "/images/blog/bridget_076_blog.jpeg", alt: "Blog 76", category: "blog" },
    { src: "/images/blog/bridget_075_blog.jpeg", alt: "Blog 75", category: "blog" },
    { src: "/images/blog/bridget_074_blog.jpeg", alt: "Blog 74", category: "blog" },
    { src: "/images/blog/bridget_073_blog.jpeg", alt: "Blog 73", category: "blog" },
    { src: "/images/blog/bridget_072_blog.jpeg", alt: "Blog 72", category: "blog" },
    { src: "/images/blog/bridget_071_blog.jpeg", alt: "Blog 71", category: "blog" },
    { src: "/images/blog/bridget_070_blog.jpeg", alt: "Blog 70", category: "blog" },
    { src: "/images/blog/bridget_069_blog.jpeg", alt: "Blog 69", category: "blog" },
    { src: "/images/blog/bridget_068_blog.jpeg", alt: "Blog 68", category: "blog" },
    { src: "/images/blog/bridget_067_blog.jpeg", alt: "Blog 67", category: "blog" },
    { src: "/images/blog/bridget_066_blog.jpeg", alt: "Blog 66", category: "blog" },
    { src: "/images/blog/bridget_065_blog.jpeg", alt: "Blog 65", category: "blog" },
    { src: "/images/blog/bridget_064_blog.jpeg", alt: "Blog 64", category: "blog" },
    { src: "/images/blog/bridget_063_blog.jpeg", alt: "Blog 63", category: "blog" },
    { src: "/images/blog/bridget_062_blog.jpeg", alt: "Blog 62", category: "blog" },
    { src: "/images/blog/bridget_061_blog.jpeg", alt: "Blog 61", category: "blog"},

    
  ]
  return images
}

export const getBlogImages = () => {
  return getImages().filter(img => img.category === 'blog')
}


// Helper function to get images by category
export const getImagesByCategory = (category: string) => {
  return getImages().filter(img => img.category === category)
}

// Get all images for a specific category
export const getAllImages = () => getImages()
export const getEntropyImages = () => getImagesByCategory('entropy')